### ISSUE TITLE
Improve component folder structure

### ISSUE THREAD

**Issue by IgorKrupenja** [IgorKrupenja/zaino#533]
## General

- [ ] search for "export type " and consider moving to separate files - maybe move to common folder
- [ ] same for "export enum " - maybe move to common folder
- [x] sort prop types alphabetically ASC
- [x] https://www.joshwcomeau.com/react/file-structure/
- [x] Privacy policy - add Page in name?
- [x] Find a good general structure
- [x] Folder names should be lowercase if not Component.

## Per component

- [ ] CSS: Current approach mostly OK except for using CSS classes from other components. E.g. ComponentA should only use classes defined in ComponentA's styles.scss and not from ComponentB's styles.scss.
- [ ] Arrange CSS properties alphabetically, including TS files
- [ ] Remove excessive comments
- [ ] Rename style files to `Component.scss`

## Components

- [x] App
- [x] other
- [x] labels - ready but need to merge branch
- [x] item-modal
- [x] dashboard - only ItemFilters
- [x] common - except components with renamed SCSS files **AND** only in misc and selects remaining these
- [ ] search for `style.scss`
